// Generated by CoffeeScript 1.10.0
$('button').click(function() {
  var flickAPI, flickrOptions, renderPhotos, vehicle;
  $('button').removeClass('selected');
  $(this).addClass('selected');
  flickAPI = "https://api.flickr.com/services/feeds/photos_public.gne?jsoncallback=?";
  vehicle = $(this).text();
  flickrOptions = {
    tags: vehicle,
    format: "json"
  };
  renderPhotos = function(data) {
    var i, len, photo, photosHtml, ref;
    photosHtml = '<ul>';
    ref = data.items;
    for (i = 0, len = ref.length; i < len; i++) {
      photo = ref[i];
      photosHtml = photosHtml + " <li class=\"grid-25 tablet-grid-50\">";
      photosHtml = photosHtml + " <a href=\"#\" class=\"image\">";
      photosHtml = photosHtml + " <img src=\"" + photo.media.m + "\" ></a></li>";
    }
    photosHtml = photosHtml + "</ul>";
    return $('#photos').html(photosHtml);
  };
  return $.getJSON(flickAPI, flickrOptions, renderPhotos);
});
